name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # windows-latest は別途対応
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Check npm and node versions
      shell: bash
      run: |
        echo "Node version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          dir
        else
          ls -la
        fi
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci --loglevel=error || (echo "npm ci failed with error:" && npm ci --loglevel=verbose && exit 1)
    
    - name: Run lint
      run: |
        echo "Running ESLint..."
        npm run lint || (echo "Lint failed. Continuing with tests..." && true)
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm test
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"
    
    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20.x'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    
    - name: Check npm and node versions
      shell: bash
      run: |
        echo "Node version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          dir
        else
          ls -la
        fi
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci --loglevel=error || (echo "npm ci failed with error:" && npm ci --loglevel=verbose && exit 1)
    
    - name: Build
      run: npm run build
    
    - name: Check if version changed
      id: version
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        
        # Check if package exists and if this version is already published
        if npm view claudy version >/dev/null 2>&1; then
          # Package exists, check if this version is published
          if npm view claudy@$CURRENT_VERSION version >/dev/null 2>&1; then
            echo "version_changed=false" >> $GITHUB_OUTPUT
          else
            echo "version_changed=true" >> $GITHUB_OUTPUT
          fi
        else
          # Package doesn't exist yet, so we should publish
          echo "version_changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Publish to npm
      if: steps.version.outputs.version_changed == 'true'
      run: |
        echo "Publishing version ${{ steps.version.outputs.current_version }} to npm..."
        npm whoami || echo "Not authenticated to npm"
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create Release
      if: steps.version.outputs.version_changed == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.current_version }}
        release_name: Release v${{ steps.version.outputs.current_version }}
        body: |
          Release v${{ steps.version.outputs.current_version }}
          
          See [CHANGELOG.md](https://github.com/douhashi/claudy/blob/main/CHANGELOG.md) for details.
        draft: false
        prerelease: false