name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Bump version
      run: |
        npm version ${{ github.event.inputs.version }} -m "chore: release v%s"
        VERSION=$(node -p "require('./package.json').version")
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Push changes
      run: |
        git push origin main
        git push origin v${{ env.VERSION }}
    
    - name: Publish to npm
      run: |
        echo "Publishing version ${{ env.VERSION }} to npm..."
        npm whoami || echo "Not authenticated to npm"
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        body: |
          ## 🎉 Release v${{ env.VERSION }}
          
          ### 📋 Changes
          
          Please see [CHANGELOG.md](https://github.com/douhashi/claudy/blob/main/CHANGELOG.md) for a full list of changes.
          
          ### 📦 Installation
          
          ```bash
          npm install -g claudy@${{ env.VERSION }}
          ```
        draft: false
        prerelease: false
